# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81471a47a21d4c260784a94572631e799aad067aa1d921fb368315c2210183f077d0921f54f63326852dca4e3da3fb7e1a7cfef07b16217ec3737db7b319fbd8

test:
  secret_key_base: 818ff7f25ec440fefaf2649eef07f01f8ef3b3423435313f2ca813b8a79e2ef90378a8ec17a71fdaa073060f0051b05648eb087446906166a8f1218275fad8c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
